name: CI Pipeline - Build & Push

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: cvregistryfranck.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push API
        run: |
          docker build -t cvregistryfranck.azurecr.io/api:${{ github.sha }} -t cvregistryfranck.azurecr.io/api:latest ./api
          docker push cvregistryfranck.azurecr.io/api:${{ github.sha }}
          docker push cvregistryfranck.azurecr.io/api:latest

      # 2. Build et Push du Frontend
      - name: Build and push Frontend
        run: |
          docker build -t cvregistryfranck.azurecr.io/frontend:${{ github.sha }} -t cvregistryfranck.azurecr.io/frontend:latest ./frontend
          docker push cvregistryfranck.azurecr.io/frontend:${{ github.sha }}
          docker push cvregistryfranck.azurecr.io/frontend:latest

      # 3. Build et Push du PDF Generator
      - name: Build and push PDF Generator
        run: |
          docker build -t cvregistryfranck.azurecr.io/pdf-generator:${{ github.sha }} -t cvregistryfranck.azurecr.io/pdf-generator:latest ./pdf-generator
          docker push cvregistryfranck.azurecr.io/pdf-generator:${{ github.sha }}
          docker push cvregistryfranck.azurecr.io/pdf-generator:latest
